### ISSUE TITLE
ToDo's

### ISSUE THREAD

**Issue by appijumbo** [appijumbo/CSC#1]
### Phase 1
- [x] Add Meetup API download capability to automatically generate the next meet up date for the meet up button
- [x] Connect contact form to suitable API thats Jekyll compatible
-[ ] Fix the CSS for mobile so that the Google Map displays and can still be scrolled properly
- [ ] Fix terms button so it displays the terms and conditions.Currently terms and conditions do not display when 'Terms' is clicked
- [ ] Make the club name text larger and positioned in line with the bottom of the logo when on larger screen.
- [ ] When people sign up email automatically offer link to public speaking tip and pdf's ?
### Phase 2
- [ ] Add a 'Members' page (a public page but only intended for members)
- [ ] Group resources focused on meeting roles for typical roles and needs, link descriptions to dropbox/google drive and Toastmasters guides added
- [ ] Grouped resources for general public speaking tips added
- [ ] Add Facebook and perhaps other social media to act as news feeds
- [ ] Use Meetup or Facebook private API to create polls for who want to do the next role. 
### Phase 3
- [ ] Change single CSS stylesheet to a SaSS work flow
- [ ] Improve Meetup buttons presentation of dates
- [ ] Develop multi language Meetup button
